wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: global_step
    - 1: eval/front._type
      5: 1
      6:
      - 1
    - 1: eval/front.sha256
      5: 1
      6:
      - 1
    - 1: eval/front.size
      5: 1
      6:
      - 1
    - 1: eval/front.artifact_path
      5: 1
      6:
      - 1
    - 1: eval/front._latest_artifact_path
      5: 1
      6:
      - 1
    - 1: eval/front.path
      5: 1
      6:
      - 1
    - 1: eval/front.ncols
      5: 1
      6:
      - 1
    - 1: eval/front.nrows
      5: 1
      6:
      - 1
    - 1: eval/Mean Utility - GPI
      5: 1
      6:
      - 1
    - 1: iteration
      5: 1
      6:
      - 1
    python_version: 3.8.8
    session_history: code\_session_history.ipynb
    start_time: 1681755842.989876
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 7
      - 13
      - 16
      - 19
      - 23
      - 35
      4: 3.8.8
      5: 0.14.0
      8:
      - 1
      - 3
      - 5
algo:
  desc: null
  value: gpi-ls_2_obj_NormAction_lessPolicyNoise_lessHiddenLayers200
alpha:
  desc: null
  value: 0.6
batch_size:
  desc: null
  value: 128
buffer_size:
  desc: null
  value: 400000
delay_policy_update:
  desc: null
  value: 2
dyna:
  desc: null
  value: false
dynamics_min_uncertainty:
  desc: null
  value: 2.0
dynamics_net_arch:
  desc: null
  value:
  - 200
  - 200
  - 200
  - 200
dynamics_real_ratio:
  desc: null
  value: 0.1
dynamics_rollout_batch_size:
  desc: null
  value: 10000
dynamics_rollout_freq:
  desc: null
  value: 250
dynamics_rollout_len:
  desc: null
  value: 5
dynamics_rollout_starts:
  desc: null
  value: 1000
dynamics_train_freq:
  desc: null
  value: 250
env_id:
  desc: null
  value: water-reservoir-v0
gamma:
  desc: null
  value: 0.99
gradient_updates:
  desc: null
  value: 1
known_front:
  desc: null
  value: null
learning_rate:
  desc: null
  value: 0.0003
learning_starts:
  desc: null
  value: 100
min_priority:
  desc: null
  value: 0.1
net_arch:
  desc: null
  value:
  - 200
num_q_nets:
  desc: null
  value: 2
per:
  desc: null
  value: true
policy_noise:
  desc: null
  value: 0.002
ref_point:
  desc: null
  value:
  - 0.0
  - 0.0
seed:
  desc: null
  value: null
tau:
  desc: null
  value: 0.005
