wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/GPI/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: global_step
    - 1: dynamics/predictions._type
      5: 1
      6:
      - 1
    - 1: dynamics/predictions.sha256
      5: 1
      6:
      - 1
    - 1: dynamics/predictions.size
      5: 1
      6:
      - 1
    - 1: dynamics/predictions.path
      5: 1
      6:
      - 1
    - 1: dynamics/predictions.format
      5: 1
      6:
      - 1
    - 1: dynamics/predictions.width
      5: 1
      6:
      - 1
    - 1: dynamics/predictions.height
      5: 1
      6:
      - 1
    - 1: eval/front._type
      5: 1
      6:
      - 1
    - 1: eval/front.sha256
      5: 1
      6:
      - 1
    - 1: eval/front.size
      5: 1
      6:
      - 1
    - 1: eval/front.artifact_path
      5: 1
      6:
      - 1
    - 1: eval/front._latest_artifact_path
      5: 1
      6:
      - 1
    - 1: eval/front.path
      5: 1
      6:
      - 1
    - 1: eval/front.ncols
      5: 1
      6:
      - 1
    - 1: eval/front.nrows
      5: 1
      6:
      - 1
    - 1: eval/Mean Utility - GPI
      5: 1
      6:
      - 1
    - 1: iteration
      5: 1
      6:
      - 1
    python_version: 3.8.8
    start_time: 1679596205.06044
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 7
      - 13
      - 16
      - 23
      - 35
      4: 3.8.8
      5: 0.13.11
      8:
      - 3
      - 5
alpha:
  desc: null
  value: 0.6
batch_size:
  desc: null
  value: 128
buffer_size:
  desc: null
  value: 400000
delay_policy_update:
  desc: null
  value: 2
dyna:
  desc: null
  value: false
dynamics_min_uncertainty:
  desc: null
  value: 2.0
dynamics_net_arch:
  desc: null
  value:
  - 200
  - 200
  - 200
  - 200
dynamics_real_ratio:
  desc: null
  value: 0.1
dynamics_rollout_len:
  desc: null
  value: 5
env_id:
  desc: null
  value: water-reservoir-v0
gamma:
  desc: null
  value: 0.99
gradient_updates:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0003
learning_starts:
  desc: null
  value: 100
min_priority:
  desc: null
  value: 0.1
net_arch:
  desc: null
  value:
  - 256
  - 256
num_q_nets:
  desc: null
  value: 2
per:
  desc: null
  value: true
policy_noise:
  desc: null
  value: 0.2
tau:
  desc: null
  value: 0.005
